### ISSUE TITLE
BossEventPacket PR for colors missed a field

### ISSUE THREAD

**Issue by thebigsmileXD** [pmmp/BedrockProtocol#109]
Introduced in https://github.com/pmmp/BedrockProtocol/commit/c9e1f76670d3097d3978abf33b8673bc93961ec6

https://github.com/pmmp/BedrockProtocol/blob/b455a742779fee94d25f931cc2cbf6b2c5d61c1f/src/BossEventPacket.php#L100
should be
```diff
-		$result->color = 0; //hardcoded due to being useless
+		$result->color = $this->color;
```

**Comment by dktapps** [comment]
You can't use $this inside a static method. An extra parameter would have to be added.
