### ISSUE TITLE
Error: Whenever i use CorrectPlayerMovePredictionPacket, i get server sent broken packet

### ISSUE THREAD

**Issue by ItsToxicGG** [pmmp/BedrockProtocol#257]
Usage:

```php
        $dx = PlayerDX::getDXPlayer($player);

        $pkt = CorrectPlayerMovePredictionPacket::create($dx->getAuthInput()->getPosition(), $dx->getAuthInput()->getDelta(), $player->isOnGround(), $dx->getAuthInput()->getTick(), 1);

        NetworkBroadcastUtils::broadcastPackets($player->getServer()->getOnlinePlayers(), [$pkt]);
```
i also tried
```php
        $dx = PlayerDX::getDXPlayer($player);

        $pkt = CorrectPlayerMovePredictionPacket::create($dx->getAuthInput()->getPosition(), $dx->getAuthInput()->getDelta(), $player->isOnGround(), $dx->getAuthInput()->getTick(), 1);

        $player->getNetworkSession()->sendDataPacket($pkt);
```

i gave up till one time i tried and accidentally had a plugin on that told me this when i got kicked for CorrectPlayerMovePredictionPacket "server sent broken packet" 

Received [0] Packet Violation message: 'BinaryStream read() incomplete
readNoHeader failed! packetId: 161' Packet ID: 0xa1

Im not sure is it my side or ?

context: getAuthInput is the PlayerAuthInputPacket

**Comment by ismaileke** [comment]
when i compared it with other sources, i realized that
```php
BedrockProtocol->CorrectPlayerMovePredictionPacket 
$out->putVector3($this->position)
$out->putVector3($this->delta)
$out->putBool($this->onGround)
$out->putUnsignedVarLong($this->tick)
$out->putByte($this->predictionType) <- here
```
`PredictionType` on top #Mojang/bedrock-protocol-docs
![image](https://github.com/user-attachments/assets/4906973a-f1c4-414f-a336-909784769281)

The final version should look like this.
```php
$out->putByte($this->predictionType)
$out->putVector3($this->position)
$out->putVector3($this->delta)
if $this->predictionType == TypeVehicle {
	$out->putVector2($this->rotation) // there is no `putVector2` in PacketSerializer
}
$out->putBool($this->onGround)
$out->putUnsignedVarLong($this->tick)
```

**Comment by ItsToxicGG** [comment]
knew it, i saw in gophertunnels protocol it looked diff to pmmp's

**Comment by Superomarking** [comment]
Seb also commented on this a while back
https://discord.com/channels/623638955262345216/637335508166377513/1265954660892803072

**Comment by dktapps** [comment]
@TwistedAsylumMC do you have any insight on this?

**Comment by Superomarking** [comment]
RewindType::Player is set to 1 in both gopher and pm, and  its checking for if the type is 1, am I missing something here?

**Comment by TwistedAsylumMC** [comment]
@Superomarking gophertunnel has vehicle for 1, not player. https://github.com/Sandertv/gophertunnel/blob/master/minecraft/protocol/packet/correct_player_move_prediction.go#L8-L11

**Comment by ismaileke** [comment]
> RewindType::Player is set to 1 in both gopher and pm, and its checking for if the type is 1, am I missing something here?

no, look

PM: "wrong"
![image](https://github.com/user-attachments/assets/6afb1785-5073-4c0f-a122-f0d9a1ee6353)
Gophertunnel:
![image](https://github.com/user-attachments/assets/b916b3f4-e814-4280-9c7e-093cb38004be)

**Comment by Superomarking** [comment]
Gotcha, miss checked
So PM has it wrongly translated, may I make a PR for this?

**Comment by ismaileke** [comment]
> Gotcha, miss checked So PM has it wrongly translated, may I make a PR for this?

why not

**Comment by Superomarking** [comment]
Update: Check #259
