### ISSUE TITLE
Adding CameraTargetInstruction to CameraInstructionPacket results in broken packet

### ISSUE THREAD

**Issue by LuciaDX** [pmmp/BedrockProtocol#268]
When i add target instruction it results in broken packet because for some reason putActorUniqueId isnt right.
![image](https://github.com/user-attachments/assets/732d0963-a001-43bb-8784-9c370a6968dd)

Changing this to putLLong fixes the problem
![image](https://github.com/user-attachments/assets/f059bc8c-8435-4cf0-872e-d11097f30046)

**Comment by ismaileke** [comment]
what about 'putUnsignedVarLong()'

**Comment by LuciaDX** [comment]
> what about 'putUnsignedVarLong()'

It says that its not usigned on their docs
![image](https://github.com/user-attachments/assets/c4488c61-f448-400b-acbb-d7cbaa7649b5)

I tried using long, it doesnt break packet but game refuses to read it so i think this is long long and not others because every single one breaks the packet

**Comment by nicholass003** [comment]
> When i add target instruction it results in broken packet because for some reason putActorUniqueId isnt right. ![image](https://private-user-images.githubusercontent.com/82135652/364929845-732d0963-a001-43bb-8784-9c370a6968dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTA5OTQsIm5iZiI6MTcyNTU5MDY5NCwicGF0aCI6Ii84MjEzNTY1Mi8zNjQ5Mjk4NDUtNzMyZDA5NjMtYTAwMS00M2JiLTg3ODQtOWMzNzBhNjk2OGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDAyNDQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZTdmMTg2MDIwMzNjMDUyYTE1MWM5ZmYyZTFmNjNhYjE2YzllOWVkZWMzNGI0MTYzYmM5ZDZjNDI2YTEyZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PPcNw-3ywmdZGQzL5j8SzZuwtAubtt_sKOwlgZbqQjQ)
> 
> Changing this to putLLong fixes the problem ![image](https://private-user-images.githubusercontent.com/82135652/364930351-f059bc8c-8435-4cf0-872e-d11097f30046.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTA5OTQsIm5iZiI6MTcyNTU5MDY5NCwicGF0aCI6Ii84MjEzNTY1Mi8zNjQ5MzAzNTEtZjA1OWJjOGMtODQzNS00Y2YwLTg3MmUtZDExMDk3ZjMwMDQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDAyNDQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljZDdlZTUxN2Q1ZDk4YWNlYzE3YWIyNmQ4YjM0MzEzNjFhYzcwNDgxMThmNjRlMDlkNjM4YTQ4ZjAyZTdiMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wiwfupNhLawV-Ptj4dinQG2ngDxa07293WFASR4248s)

yes, that's right, it must be the same as this, because it's the same type
https://github.com/pmmp/BedrockProtocol/blob/master/src/types/AbilitiesData.php#L58

CameraTargetInstruction.targetActorUniqueId
source: https://github.com/Mojang/bedrock-protocol-docs/blob/main/changelog_712_7_16_24.md
```
Changelogs: changelog_712_7_16_24.md
* Added mTargetActorId (int64_t)
```

AbilitiesData.targetActorUniqueId
source: https://github.com/Mojang/bedrock-protocol-docs/blob/main/previous_changelogs/changelog_553_08_31_22.md
```
Changelogs: changelog_553_08_31_22.md
* Add mTargetPlayer.rawID (int64_t)
```
