### ISSUE TITLE
Invalid command parameter types

### ISSUE THREAD

**Issue by Tobias-2006** [pmmp/BedrockProtocol#62]
Some parameter types in [AvailableCommandsPacket](https://github.com/pmmp/BedrockProtocol/blob/4f50214af0d55de898f02df9ed112ea29352d000/src/AvailableCommandsPacket.php) have changed with the update 1.18.30 and are now invalid.

---

`ARG_TYPE_WILDCARD_TARGET = 0x08` -> `ARG_TYPE_WILDCARD_TARGET = 0x09`
`ARG_TYPE_STRING = 0x20` -> `ARG_TYPE_STRING = 0x26`
`ARG_TYPE_POSITION = 0x28` -> `ARG_TYPE_POSITION = 0x2F`
`ARG_TYPE_MESSAGE = 0x2c` -> `ARG_TYPE_MESSAGE = 0x32`
`ARG_TYPE_RAWTEXT = 0x2e` -> `ARG_TYPE_RAWTEXT = 0x34`
`ARG_TYPE_JSON = 0x32` -> `ARG_TYPE_JSON = 0x38`
`ARG_TYPE_COMMAND = 0x3f` -> `ARG_TYPE_COMMAND = 0x45`

and

`ARG_TYPE_BLOCK_POSITION = 0x2E`

This fact was not tested in detail!

**Comment by jasonwynn10** [comment]
Relates to #60

**Comment by sky-min** [comment]
Oh, I thought ARG_TYPE_WILDCARD.Destination was deleted but changed.

**Comment by dktapps** [comment]
Fixed by 9d3cc87c4d26c002dd42aa9af20c0cd47a72018e.
