### ISSUE TITLE
Incorrect encoding of data in LevelEventGenericPacket

### ISSUE THREAD

**Issue by dktapps** [pmmp/BedrockProtocol#77]
For some reason, the CompoundTag in LevelEventGenericPacket is encoded differently from every other tag in the protocol. It's written without the header (i.e. CompoundTag->write()). This means that we can't use CachedNbt for it (in its current form, anyway).

**Comment by dktapps** [comment]
Fixing this requires changes to pocketmine/nbt, because NbtSerializer wasn't designed to be able to read or write headless tags like this.

**Comment by IvanCraft623** [comment]
Time to re-open this :P

**Comment by dktapps** [comment]
Thanks for the reminder.
